models:
  - ../../cad_models/10x6_maze_obj_1.stl
  - ../../cad_models/10x6_maze_obj_2.stl
  - ../../cad_models/10x6_walls.stl
outlets_models:
  - "!color [0.88, 0.19, 0.19, 1.00]"
  - ../../cad_models/10x6_door_left.stl
  - ../../cad_models/10x6_door_right.stl
unprocessed_wind_files: ../../wind_simulations/05ms/wind_at_cell_centers
empty_point: [0.45, 1.2, 0]
cell_size: 0.1
uniformWind: false