/* Auto-generated by genmsg_cpp for file /home/ali/ros_workspace/odor_simulation/msgs_and_srvs/msg/SourceLoc.msg */
#ifndef MSGS_AND_SRVS_MESSAGE_SOURCELOC_H
#define MSGS_AND_SRVS_MESSAGE_SOURCELOC_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace msgs_and_srvs
{
template <class ContainerAllocator>
struct SourceLoc_ {
  typedef SourceLoc_<ContainerAllocator> Type;

  SourceLoc_()
  : loc(0.0)
  {
  }

  SourceLoc_(const ContainerAllocator& _alloc)
  : loc(0.0)
  {
  }

  typedef double _loc_type;
  double loc;


  typedef boost::shared_ptr< ::msgs_and_srvs::SourceLoc_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::msgs_and_srvs::SourceLoc_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct SourceLoc
typedef  ::msgs_and_srvs::SourceLoc_<std::allocator<void> > SourceLoc;

typedef boost::shared_ptr< ::msgs_and_srvs::SourceLoc> SourceLocPtr;
typedef boost::shared_ptr< ::msgs_and_srvs::SourceLoc const> SourceLocConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::msgs_and_srvs::SourceLoc_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::msgs_and_srvs::SourceLoc_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace msgs_and_srvs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::msgs_and_srvs::SourceLoc_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::msgs_and_srvs::SourceLoc_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::msgs_and_srvs::SourceLoc_<ContainerAllocator> > {
  static const char* value() 
  {
    return "22929794d94d08907554bcf6f43d123a";
  }

  static const char* value(const  ::msgs_and_srvs::SourceLoc_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x22929794d94d0890ULL;
  static const uint64_t static_value2 = 0x7554bcf6f43d123aULL;
};

template<class ContainerAllocator>
struct DataType< ::msgs_and_srvs::SourceLoc_<ContainerAllocator> > {
  static const char* value() 
  {
    return "msgs_and_srvs/SourceLoc";
  }

  static const char* value(const  ::msgs_and_srvs::SourceLoc_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::msgs_and_srvs::SourceLoc_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float64 loc\n\
\n\
\n\
";
  }

  static const char* value(const  ::msgs_and_srvs::SourceLoc_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::msgs_and_srvs::SourceLoc_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::msgs_and_srvs::SourceLoc_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.loc);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct SourceLoc_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::msgs_and_srvs::SourceLoc_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::msgs_and_srvs::SourceLoc_<ContainerAllocator> & v) 
  {
    s << indent << "loc: ";
    Printer<double>::stream(s, indent + "  ", v.loc);
  }
};


} // namespace message_operations
} // namespace ros

#endif // MSGS_AND_SRVS_MESSAGE_SOURCELOC_H

