models:
  - ../../cad_models/ROOMS-walls.stl
outlets_models:
  - "!color [0.25, 0.25, 0.25, 1.00]"
  - ../../cad_models/ROOMS-outlet-1.stl
  - ../../cad_models/ROOMS-outlet-2.stl
  - ../../cad_models/ROOMS-outlet-3.stl
  - ../../cad_models/ROOMS-outlet-4.stl
  - ../../cad_models/ROOMS-outlet-5.stl
  - ../../cad_models/ROOMS-outlet-6.stl
unprocessed_wind_files: ../../wind_simulations/1,2,3-5,6
empty_point: [4.4, 1.55, 0.5]
cell_size: 0.1
uniformWind: false