# PARAMETERS FOR GADEN #
# ===================== #

# ================
gaden_environment:
  ros__parameters:
    verbose: false
    wait_preprocessing: false   # wait for the ok from gaden_preprocessing before running
    fixed_frame: "map"

    # Plot CAD models (Collada format .dae)
    CAD_models:
      - "!color [0.5, 0.35, 0.15]"
      - "$(var pkg_dir)/scenarios/$(var scenario)/cad_models/MAPIRlab_tables.dae"
      - "!color [0.92, 0.96, 0.96]"
      - "$(var pkg_dir)/scenarios/$(var scenario)/cad_models/MAPIRlab_walls.dae"
      - "!color [0.2, 0.2, 0.05]"
      - "$(var pkg_dir)/scenarios/$(var scenario)/cad_models/MAPIRlab_wardrobes.dae"
      - "!color [0.9, 0.3, 0.3]"
      - "$(var pkg_dir)/scenarios/$(var scenario)/cad_models/MAPIRlab_doors.dae"
      - "$(var pkg_dir)/scenarios/$(var scenario)/cad_models/MAPIRlab_windows.dae"

    # Plot 3D OccupancyGridmap
    occupancy3D_data: "$(var pkg_dir)/scenarios/$(var scenario)/OccupancyGrid3D.csv"

    # Plot gas sources
    number_of_sources: 1
    source_0_position_x: $(var source_x)
    source_0_position_y: $(var source_y)
    source_0_position_z: $(var source_z)
    source_0_scale: 0.2
    source_0_color: [0.0, 1.0, 0.0] 


# ================
gaden_filament_simulator:
  ros__parameters:
    verbose: false
    wait_preprocessing: false                                       ### wait for the ok from preprocessing before starting the simulation
    sim_time: $(var sim_time)                                       ### [sec] Total time of the gas dispersion simulation
    time_step: $(var time_step)                                     ### [sec] Time increment between snapshots. Set aprox = cell_size/max_wind_speed.
    num_filaments_sec: $(var num_filaments_sec)                     ### Num of filaments released each second
    variable_rate: $(var variable_rate)                             ### If true the number of released filaments would be random(0,numFilaments_sec)
    filament_stop_steps: $(var filament_stop_steps)    
    ppm_filament_center: $(var ppm_filament_center)                 ### [ppm] Gas concentration at the center of the 3D gaussian (filament)
    filament_initial_std: $(var filament_initial_std)               ### [cm] Sigma of the filament at t=0-> 3DGaussian shape
    filament_growth_gamma: $(var filament_growth_gamma)             ### [cm²/s] Growth ratio of the filament_std
    filament_noise_std: $(var filament_noise_std)                   ### [m] Range of the white noise added on each iteration
    gas_type: $(var gas_type)                                       ### 0=Ethanol, 1=Methane, 2=Hydrogen, 6=Acetone
    temperature: $(var temperature)                                 ### [Kelvins]
    pressure: 1.0                                                   ### [Atm]
    concentration_unit_choice: 1                                    ### 0=molecules/cm3, 1=ppm (when ppm is used, set temp and pressure accordingly)

    # In the occupancyGrid.csv file we set: cell_size, num_cells, etc. which come from the CFD wind simulation
    occupancy3D_data: "$(var pkg_dir)/scenarios/$(var scenario)/OccupancyGrid3D.csv"
    fixed_frame: "map"

    # WindFlow data (from CFD)
    wind_data: "$(var pkg_dir)/scenarios/$(var scenario)/wind_simulations/$(var wind_sim_path)"
    wind_time_step: 1.0                ### (sec) time increment between Wind snapshots

    # Loop options
    allow_looping: true
    loop_from_step: 0
    loop_to_step: 24

    # Location of the release point!
    source_position_x: $(var source_x)            ### (m)
    source_position_y: $(var source_y)            ### (m)
    source_position_z: $(var source_z)            ### (m)

    save_results: 1                    #1=true, 0=false
    results_time_step: 0.5             #(sec) Time increment between saving state to file
    results_min_time: 0.0              #(sec) Time to start saving results to file
    results_location: "$(var pkg_dir)/scenarios/$(var scenario)/gas_simulations/$(var simulation)"

# ================
gaden_player:
  ros__parameters:
    verbose: false
    player_freq: 2.0         ### (Hz) Freq for loading the simulation log_files
    initial_iteration: 0
    num_simulators: 1        ### Number of simulations to load [1-inf] (useful for multiple sources and gases)

    # Data from the "filament_simulator" pkg. Multiple sources can be set here
    simulation_data_0: "$(var pkg_dir)/scenarios/$(var scenario)/gas_simulations/$(var simulation)"
    occupancyFile: "$(var pkg_dir)/scenarios/$(var scenario)/OccupancyGrid3D.csv"

    # Loop options        
    allow_looping: false
    loop_from_iteration: 15
    loop_to_iteration: 24