# PARAMETERS FOR GADEN PREPROCESSING NODE #
# ======================================== #
gaden_preprocessing:
  ros__parameters:
    # Cell size
    cell_size: 0.1

    # CAD models of the enviroment (.stl)3
    models: 
      - "$(var pkg_dir)/scenarios/$(var scenario)/cad_models/MAPIRlab_tables.stl"
      - "$(var pkg_dir)/scenarios/$(var scenario)/cad_models/MAPIRlab_walls.stl"
      - "$(var pkg_dir)/scenarios/$(var scenario)/cad_models/MAPIRlab_wardrobes.stl"

    # CAD model of the outlets (.stl)2
    outlets_models: 
      - "$(var pkg_dir)/scenarios/$(var scenario)/cad_models/MAPIRlab_doors.stl"
      - "$(var pkg_dir)/scenarios/$(var scenario)/cad_models/MAPIRlab_windows.stl"

    # 3D Location of a point in free-space
    empty_point_x: 1.0      ### (m)
    empty_point_y: 1.0      ### (m)
    empty_point_z: 0.5      ### (m)

    # Wind Data (the node will append _i.csv to the name that is specified here)
    uniformWind: false
    wind_files: "$(var pkg_dir)/scenarios/$(var scenario)/wind_simulations/$(var wind_sim_path)"
    
    # Where to write the output files
    output_path: "$(var pkg_dir)/scenarios/$(var scenario)"