# PARAMETERS FOR GADEN PREPROCESSING NODE #
# ======================================== #

# The values are parsed from the environment configuration file and turned into LaunchConfigurations
# The idea is that you never need to touch this file directly, and the configuration files are shared by all the gaden nodes (preprocessing, filament_simulator, environment, etc)
gaden_preprocessing:
  ros__parameters:
    # Cell size
    cell_size: "$(var cell_size)"

    # CAD models of the enviroment (.stl)
    models: "$(var models)"

    # CAD model of the outlets (.stl)2
    outlets_models: "$(var outlets_models)"
    
    # 3D Location of a point in free-space
    empty_point_x: "$(var empty_point_x)"      ### (m)
    empty_point_y: "$(var empty_point_y)"      ### (m)
    empty_point_z: "$(var empty_point_z)"      ### (m)
    
    # Wind Data (the node will append _i.csv to the name that is specified here)
    uniformWind: $(var uniformWind)
    wind_files: "$(var pkg_dir)/scenarios/$(var scenario)/wind_simulations/$(var wind_files)"
    
    # Where to write the output files
    output_path: "$(var pkg_dir)/scenarios/$(var scenario)/$(var simulation)"