# PARAMETERS FOR GADEN #
# ===================== #

# ================
gaden_preprocessing:
  ros__parameters:
    projectPath: $(var pkg_dir)/scenarios/$(var scenario)/environment_configurations/$(var configuration)

# ================
gaden_environment:
  ros__parameters:
    projectPath: $(var pkg_dir)/scenarios/$(var scenario)/environment_configurations/$(var configuration)


# ================
gaden_filament_simulator:
  ros__parameters:
    projectPath: $(var pkg_dir)/scenarios/$(var scenario)/environment_configurations/$(var configuration)
    simulationID: $(var simulation)

# ================
gaden_player:
  ros__parameters:
    projectPath: $(var pkg_dir)/scenarios/$(var scenario)/environment_configurations/$(var configuration)
    playbackID: "$(var playback)"
